---
name: Publish Python Package

description: Build and publish a Python package to a Python package repository.

inputs:
  out_dir:
    description: "Directory where builds are saved to."
    required: false
    default: "dist/"

runs:
  using: "composite"
  steps:
    - name: Install pypa/build
      shell: bash
      run: |
        python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      shell: bash
      run: python -m build --sdist --wheel --outdir ${{ inputs.out_dir }}

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ env.PYPI_REPO_URL }}
        verbose: true
